apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: mq-consumer
  namespace: govtech
spec:
  enableMetrics: false
  license:
    accept: true
    license: L-APEH-CJUCNR
    use: CloudPakForIntegrationProduction
  pod:
    containers:
      runtime:
        resources:
          limits:
            cpu: 300m
            memory: 368Mi
          requests:
            cpu: 300m
            memory: 368Mi
  adminServerSecure: true
  router:
    timeout: 120s
  designerFlowsOperationMode: disabled
  createDashboardUsers: false
  service:
    endpointType: http
  version: '12.0'
  replicas: 1
  barURL: 'https://mattar555.github.io/idp-ace-artefacts/idp-fry-simple.bar'
  configurations:
    - ace-app-config
